#微服务配置
spring:
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 9162b69e-eadc-4f8a-b98c-c674f025b14a
        group: xuecheng-plus-project
        username: nacos
        password: nacos
        enabled: true
      config:
        username: nacos
        password: nacos
        enabled: true
        namespace: 9162b69e-eadc-4f8a-b98c-c674f025b14a
        group: xuecheng-plus-project
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: logging-${spring.profiles.active}.yaml
            group: xuecheng-plus-common
            refresh: true
  #        extension-configs:
  #          - data-id: ${spring.application.name}-${spring.profiles.active}.yaml
  #            group: xuecheng-plus-project
  #            refresh: true
  profiles:
    active: dev





